name: Aura IP Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  hunt-and-update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y whois

      - name: Run IP Hunter Script
        env:
          # --- 【核心修复】 ---
          # 我们在这里添加了新的 CF_ZONE_NAME Secret
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_RECORD_NAME: ${{ secrets.CF_RECORD_NAME }}
          CF_ZONE_NAME: ${{ secrets.CF_ZONE_NAME }}
        run: |
          chmod +x ./hunter.sh
          ./hunter.sh
