name: Aura IP Hunter

on:
  # 允许我们手动从 GitHub 的 Actions 页面触发
  workflow_dispatch:

  # 设置自动化调度。这里的例子是每天 UTC 时间的凌晨 0 点运行一次。
  # 我们可以稍后再调整这个 cron 时间表。
  schedule:
    - cron: '0 0 * * *'

jobs:
  hunt-and-update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4

      - name: Run IP Hunter Script
        env:
          # 我们稍后会在 GitHub 仓库的设置中配置这些 Secrets
          # 这是向脚本安全传递凭据的最佳方式
          CF_API_TOKEN: \${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: \${{ secrets.CF_ZONE_ID }}
          CF_RECORD_NAME: \${{ secrets.CF_RECORD_NAME }}
        run: |
          # 赋予我们的核心脚本执行权限
          chmod +x ./hunter.sh
          # 运行脚本
          ./hunter.sh
